[build]
  publish = "public"

[functions]
  directory = "netlify/functions"

# Rewrite all frontend "/api/*" requests directly to our serverless Express function
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

# Redirect all remaining client paths to index.html for React/Vanilla SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
